from typing import Protocol


class OpenAIClient(Protocol):
    def summarize(self, document_text: str) -> dict:
        ...

    def extract_clauses(self, document_text: str) -> dict:
        ...

    def assess_risks(self, document_text: str, clauses: list[dict]) -> dict:
        ...


class MockOpenAIClient:
    def summarize(self, document_text: str) -> dict:
        return {
            "document_type": "contract",
            "short_summary": "Sample structured summary generated by the mock client.",
            "key_points": [
                "Demo summary point 1",
                "Demo summary point 2",
                "Demo summary point 3",
            ],
        }

    def extract_clauses(self, document_text: str) -> dict:
        return {
            "clauses": [
                {
                    "heading": "Termination",
                    "category": "termination",
                    "extracted_text": "Either party may terminate for material breach.",
                    "confidence": 0.92,
                    "page_reference": 1,
                }
            ]
        }

    def assess_risks(self, document_text: str, clauses: list[dict]) -> dict:
        return {
            "risk_flags": [
                {
                    "severity": "medium",
                    "title": "Termination rights are limited",
                    "description": "The document appears to have narrow termination conditions.",
                    "recommendation": "Review whether broader termination rights are required.",
                    "impacted_clause_id": "clause_1",
                }
            ]
        }
